### PR TITLE
Fix quoting for columns containing an underscore in the name

### LINKED ISSUE #23: Fix quoting for columns containing an underscore in the name
For tables contained columns starting with underscore VSATHENA added backticks around the column name. 
This leads to an error on Athena side. 

However, the query runs fine when adding double quotes instead.
I assume [AthenaIdentifier.java, line 24](https://github.com/exasol/athena-virtual-schema/blob/main/src/main/java/com/exasol/adapter/dialects/athena/AthenaIdentifier.java#L24) is the corresponding line in the code.

To my understanding it should always be doublequotes, backticks are only used for CREATE TABLE statements in Athena.

### PR DESCRIPTION
**Pull request by ckunki**
fixes #23

### CODE REVIEW

File: src/main/java/com/exasol/adapter/dialects/athena/AthenaIdentifier.java [hunk 1]
```diff
@@ -22,14 +22,16 @@ private AthenaIdentifier(final String id) {
...
-            return quoteWithBackticks(this.id);
-        } else {
-            return quoteWithDoubleQuotes(this.id);
-        }
+        return quoteWithDoubleQuotes(this.id);
     }
 
-    private String quoteWithBackticks(final String identifier) {
+    /**
+     * Only required for {@code CREATE TABLE} statements.
```
Comment (redcatbear) [inline src/main/java/com/exasol/adapter/dialects/athena/AthenaIdentifier.java]:
```suggestion
    /**
     * Quote a given identifier with backticks ({@code `}).
     * <p>
     * Only required for {@code CREATE TABLE} statements.
     * </p>
```

**Review by redcatbear — DISMISSED** [review]

File: pom.xml [hunk 2]
```diff
@@ -8,7 +8,7 @@
     <description>Virtual Schema for connecting Athena as a data source to Exasol</description>
     <url>https://github.com/exasol/athena-virtual-schema/</url>
     <properties>
-        <vscjdbc.version>10.1.0</vscjdbc.version>
+        <vscjdbc.version>10.5.0</vscjdbc.version>
     </properties>
     <repositories>
         <repository>
```
Comment (kaklakariada) [inline pom.xml]: Delete the maven.exasol.com repo

**Review by kaklakariada — CHANGES_REQUESTED** [review]

**Review by kaklakariada — DISMISSED** [review]

**Review by kaklakariada — APPROVED** [review]
